// source: message.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = function () {
  return this || window || global || self || Function('return this')();
}.call(null);

var common_common_pb = require('./common_pb.js');
goog.object.extend(proto, common_common_pb);
goog.exportSymbol('proto.io.rulelogic.api.MessagePullRequest', null, global);
goog.exportSymbol('proto.io.rulelogic.api.MessagePullResponse', null, global);
goog.exportSymbol('proto.io.rulelogic.api.MessagePushRequest', null, global);
goog.exportSymbol('proto.io.rulelogic.api.MessagePushResponse', null, global);
goog.exportSymbol('proto.io.rulelogic.api.Payload', null, global);
goog.exportSymbol('proto.io.rulelogic.api.PullInitRequest', null, global);
goog.exportSymbol('proto.io.rulelogic.api.PullInitResponse', null, global);
goog.exportSymbol('proto.io.rulelogic.api.PushInitRequest', null, global);
goog.exportSymbol('proto.io.rulelogic.api.PushInitResponse', null, global);
goog.exportSymbol('proto.io.rulelogic.api.actionInstructionEnum', null, global);
goog.exportSymbol('proto.io.rulelogic.api.eventInstructionEnum', null, global);
goog.exportSymbol(
  'proto.io.rulelogic.api.eventMessageReasonEnum',
  null,
  global
);
goog.exportSymbol('proto.io.rulelogic.api.instructionTypeEnum', null, global);
goog.exportSymbol(
  'proto.io.rulelogic.api.messageSubscriptionEnum',
  null,
  global
);
goog.exportSymbol('proto.io.rulelogic.api.messageTopicEnum', null, global);
goog.exportSymbol('proto.io.rulelogic.api.ruleInstructionEnum', null, global);
goog.exportSymbol('proto.io.rulelogic.api.ruleMessageReasonEnum', null, global);
goog.exportSymbol('proto.io.rulelogic.api.statusEnum', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.rulelogic.api.PullInitRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.rulelogic.api.PullInitRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.rulelogic.api.PullInitRequest.displayName =
    'proto.io.rulelogic.api.PullInitRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.rulelogic.api.PushInitResponse = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.rulelogic.api.PushInitResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.rulelogic.api.PushInitResponse.displayName =
    'proto.io.rulelogic.api.PushInitResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.rulelogic.api.PushInitRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.rulelogic.api.PushInitRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.rulelogic.api.PushInitRequest.displayName =
    'proto.io.rulelogic.api.PushInitRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.rulelogic.api.PullInitResponse = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.rulelogic.api.PullInitResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.rulelogic.api.PullInitResponse.displayName =
    'proto.io.rulelogic.api.PullInitResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.rulelogic.api.MessagePullResponse = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.rulelogic.api.MessagePullResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.rulelogic.api.MessagePullResponse.displayName =
    'proto.io.rulelogic.api.MessagePullResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.rulelogic.api.MessagePushResponse = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.rulelogic.api.MessagePushResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.rulelogic.api.MessagePushResponse.displayName =
    'proto.io.rulelogic.api.MessagePushResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.rulelogic.api.MessagePullRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.rulelogic.api.MessagePullRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.rulelogic.api.MessagePullRequest.displayName =
    'proto.io.rulelogic.api.MessagePullRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.rulelogic.api.MessagePushRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.rulelogic.api.MessagePushRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.rulelogic.api.MessagePushRequest.displayName =
    'proto.io.rulelogic.api.MessagePushRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.rulelogic.api.Payload = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.rulelogic.api.Payload, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.rulelogic.api.Payload.displayName = 'proto.io.rulelogic.api.Payload';
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.io.rulelogic.api.PullInitRequest.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.io.rulelogic.api.PullInitRequest.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.io.rulelogic.api.PullInitRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.io.rulelogic.api.PullInitRequest.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        messagetopic: jspb.Message.getFieldWithDefault(msg, 1, 0),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.rulelogic.api.PullInitRequest}
 */
proto.io.rulelogic.api.PullInitRequest.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.rulelogic.api.PullInitRequest();
  return proto.io.rulelogic.api.PullInitRequest.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.rulelogic.api.PullInitRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.rulelogic.api.PullInitRequest}
 */
proto.io.rulelogic.api.PullInitRequest.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {!proto.io.rulelogic.api.messageTopicEnum} */ (
          reader.readEnum()
        );
        msg.setMessagetopic(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.rulelogic.api.PullInitRequest.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.io.rulelogic.api.PullInitRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.rulelogic.api.PullInitRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rulelogic.api.PullInitRequest.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined;
  f = message.getMessagetopic();
  if (f !== 0.0) {
    writer.writeEnum(1, f);
  }
};

/**
 * optional messageTopicEnum messageTopic = 1;
 * @return {!proto.io.rulelogic.api.messageTopicEnum}
 */
proto.io.rulelogic.api.PullInitRequest.prototype.getMessagetopic = function () {
  return /** @type {!proto.io.rulelogic.api.messageTopicEnum} */ (
    jspb.Message.getFieldWithDefault(this, 1, 0)
  );
};

/**
 * @param {!proto.io.rulelogic.api.messageTopicEnum} value
 * @return {!proto.io.rulelogic.api.PullInitRequest} returns this
 */
proto.io.rulelogic.api.PullInitRequest.prototype.setMessagetopic = function (
  value
) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.io.rulelogic.api.PushInitResponse.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.io.rulelogic.api.PushInitResponse.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.io.rulelogic.api.PushInitResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.io.rulelogic.api.PushInitResponse.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        responsestatus:
          (f = msg.getResponsestatus()) &&
          common_common_pb.ResponseStatus.toObject(includeInstance, f),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.rulelogic.api.PushInitResponse}
 */
proto.io.rulelogic.api.PushInitResponse.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.rulelogic.api.PushInitResponse();
  return proto.io.rulelogic.api.PushInitResponse.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.rulelogic.api.PushInitResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.rulelogic.api.PushInitResponse}
 */
proto.io.rulelogic.api.PushInitResponse.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = new common_common_pb.ResponseStatus();
        reader.readMessage(
          value,
          common_common_pb.ResponseStatus.deserializeBinaryFromReader
        );
        msg.setResponsestatus(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.rulelogic.api.PushInitResponse.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter();
    proto.io.rulelogic.api.PushInitResponse.serializeBinaryToWriter(
      this,
      writer
    );
    return writer.getResultBuffer();
  };

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.rulelogic.api.PushInitResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rulelogic.api.PushInitResponse.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined;
  f = message.getResponsestatus();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_common_pb.ResponseStatus.serializeBinaryToWriter
    );
  }
};

/**
 * optional ResponseStatus responseStatus = 1;
 * @return {?proto.io.rulelogic.api.ResponseStatus}
 */
proto.io.rulelogic.api.PushInitResponse.prototype.getResponsestatus =
  function () {
    return /** @type{?proto.io.rulelogic.api.ResponseStatus} */ (
      jspb.Message.getWrapperField(this, common_common_pb.ResponseStatus, 1)
    );
  };

/**
 * @param {?proto.io.rulelogic.api.ResponseStatus|undefined} value
 * @return {!proto.io.rulelogic.api.PushInitResponse} returns this
 */
proto.io.rulelogic.api.PushInitResponse.prototype.setResponsestatus = function (
  value
) {
  return jspb.Message.setWrapperField(this, 1, value);
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.io.rulelogic.api.PushInitResponse} returns this
 */
proto.io.rulelogic.api.PushInitResponse.prototype.clearResponsestatus =
  function () {
    return this.setResponsestatus(undefined);
  };

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.rulelogic.api.PushInitResponse.prototype.hasResponsestatus =
  function () {
    return jspb.Message.getField(this, 1) != null;
  };

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.io.rulelogic.api.PushInitRequest.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.io.rulelogic.api.PushInitRequest.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.io.rulelogic.api.PushInitRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.io.rulelogic.api.PushInitRequest.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        messagetopic: jspb.Message.getFieldWithDefault(msg, 1, 0),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.rulelogic.api.PushInitRequest}
 */
proto.io.rulelogic.api.PushInitRequest.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.rulelogic.api.PushInitRequest();
  return proto.io.rulelogic.api.PushInitRequest.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.rulelogic.api.PushInitRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.rulelogic.api.PushInitRequest}
 */
proto.io.rulelogic.api.PushInitRequest.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {!proto.io.rulelogic.api.messageTopicEnum} */ (
          reader.readEnum()
        );
        msg.setMessagetopic(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.rulelogic.api.PushInitRequest.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.io.rulelogic.api.PushInitRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.rulelogic.api.PushInitRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rulelogic.api.PushInitRequest.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined;
  f = message.getMessagetopic();
  if (f !== 0.0) {
    writer.writeEnum(1, f);
  }
};

/**
 * optional messageTopicEnum messageTopic = 1;
 * @return {!proto.io.rulelogic.api.messageTopicEnum}
 */
proto.io.rulelogic.api.PushInitRequest.prototype.getMessagetopic = function () {
  return /** @type {!proto.io.rulelogic.api.messageTopicEnum} */ (
    jspb.Message.getFieldWithDefault(this, 1, 0)
  );
};

/**
 * @param {!proto.io.rulelogic.api.messageTopicEnum} value
 * @return {!proto.io.rulelogic.api.PushInitRequest} returns this
 */
proto.io.rulelogic.api.PushInitRequest.prototype.setMessagetopic = function (
  value
) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.io.rulelogic.api.PullInitResponse.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.io.rulelogic.api.PullInitResponse.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.io.rulelogic.api.PullInitResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.io.rulelogic.api.PullInitResponse.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        responsestatus:
          (f = msg.getResponsestatus()) &&
          common_common_pb.ResponseStatus.toObject(includeInstance, f),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.rulelogic.api.PullInitResponse}
 */
proto.io.rulelogic.api.PullInitResponse.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.rulelogic.api.PullInitResponse();
  return proto.io.rulelogic.api.PullInitResponse.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.rulelogic.api.PullInitResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.rulelogic.api.PullInitResponse}
 */
proto.io.rulelogic.api.PullInitResponse.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = new common_common_pb.ResponseStatus();
        reader.readMessage(
          value,
          common_common_pb.ResponseStatus.deserializeBinaryFromReader
        );
        msg.setResponsestatus(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.rulelogic.api.PullInitResponse.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter();
    proto.io.rulelogic.api.PullInitResponse.serializeBinaryToWriter(
      this,
      writer
    );
    return writer.getResultBuffer();
  };

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.rulelogic.api.PullInitResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rulelogic.api.PullInitResponse.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined;
  f = message.getResponsestatus();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_common_pb.ResponseStatus.serializeBinaryToWriter
    );
  }
};

/**
 * optional ResponseStatus responseStatus = 1;
 * @return {?proto.io.rulelogic.api.ResponseStatus}
 */
proto.io.rulelogic.api.PullInitResponse.prototype.getResponsestatus =
  function () {
    return /** @type{?proto.io.rulelogic.api.ResponseStatus} */ (
      jspb.Message.getWrapperField(this, common_common_pb.ResponseStatus, 1)
    );
  };

/**
 * @param {?proto.io.rulelogic.api.ResponseStatus|undefined} value
 * @return {!proto.io.rulelogic.api.PullInitResponse} returns this
 */
proto.io.rulelogic.api.PullInitResponse.prototype.setResponsestatus = function (
  value
) {
  return jspb.Message.setWrapperField(this, 1, value);
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.io.rulelogic.api.PullInitResponse} returns this
 */
proto.io.rulelogic.api.PullInitResponse.prototype.clearResponsestatus =
  function () {
    return this.setResponsestatus(undefined);
  };

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.rulelogic.api.PullInitResponse.prototype.hasResponsestatus =
  function () {
    return jspb.Message.getField(this, 1) != null;
  };

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.io.rulelogic.api.MessagePullResponse.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.io.rulelogic.api.MessagePullResponse.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.io.rulelogic.api.MessagePullResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.io.rulelogic.api.MessagePullResponse.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        payload: jspb.Message.getFieldWithDefault(msg, 1, ''),
        responsestatus:
          (f = msg.getResponsestatus()) &&
          common_common_pb.ResponseStatus.toObject(includeInstance, f),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.rulelogic.api.MessagePullResponse}
 */
proto.io.rulelogic.api.MessagePullResponse.deserializeBinary = function (
  bytes
) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.rulelogic.api.MessagePullResponse();
  return proto.io.rulelogic.api.MessagePullResponse.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.rulelogic.api.MessagePullResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.rulelogic.api.MessagePullResponse}
 */
proto.io.rulelogic.api.MessagePullResponse.deserializeBinaryFromReader =
  function (msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
        case 1:
          var value = /** @type {string} */ (reader.readString());
          msg.setPayload(value);
          break;
        case 2:
          var value = new common_common_pb.ResponseStatus();
          reader.readMessage(
            value,
            common_common_pb.ResponseStatus.deserializeBinaryFromReader
          );
          msg.setResponsestatus(value);
          break;
        default:
          reader.skipField();
          break;
      }
    }
    return msg;
  };

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.rulelogic.api.MessagePullResponse.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter();
    proto.io.rulelogic.api.MessagePullResponse.serializeBinaryToWriter(
      this,
      writer
    );
    return writer.getResultBuffer();
  };

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.rulelogic.api.MessagePullResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rulelogic.api.MessagePullResponse.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined;
  f = message.getPayload();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
  f = message.getResponsestatus();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      common_common_pb.ResponseStatus.serializeBinaryToWriter
    );
  }
};

/**
 * optional string payload = 1;
 * @return {string}
 */
proto.io.rulelogic.api.MessagePullResponse.prototype.getPayload = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''));
};

/**
 * @param {string} value
 * @return {!proto.io.rulelogic.api.MessagePullResponse} returns this
 */
proto.io.rulelogic.api.MessagePullResponse.prototype.setPayload = function (
  value
) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional ResponseStatus responseStatus = 2;
 * @return {?proto.io.rulelogic.api.ResponseStatus}
 */
proto.io.rulelogic.api.MessagePullResponse.prototype.getResponsestatus =
  function () {
    return /** @type{?proto.io.rulelogic.api.ResponseStatus} */ (
      jspb.Message.getWrapperField(this, common_common_pb.ResponseStatus, 2)
    );
  };

/**
 * @param {?proto.io.rulelogic.api.ResponseStatus|undefined} value
 * @return {!proto.io.rulelogic.api.MessagePullResponse} returns this
 */
proto.io.rulelogic.api.MessagePullResponse.prototype.setResponsestatus =
  function (value) {
    return jspb.Message.setWrapperField(this, 2, value);
  };

/**
 * Clears the message field making it undefined.
 * @return {!proto.io.rulelogic.api.MessagePullResponse} returns this
 */
proto.io.rulelogic.api.MessagePullResponse.prototype.clearResponsestatus =
  function () {
    return this.setResponsestatus(undefined);
  };

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.rulelogic.api.MessagePullResponse.prototype.hasResponsestatus =
  function () {
    return jspb.Message.getField(this, 2) != null;
  };

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.io.rulelogic.api.MessagePushResponse.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.io.rulelogic.api.MessagePushResponse.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.io.rulelogic.api.MessagePushResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.io.rulelogic.api.MessagePushResponse.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        responsestatus:
          (f = msg.getResponsestatus()) &&
          common_common_pb.ResponseStatus.toObject(includeInstance, f),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.rulelogic.api.MessagePushResponse}
 */
proto.io.rulelogic.api.MessagePushResponse.deserializeBinary = function (
  bytes
) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.rulelogic.api.MessagePushResponse();
  return proto.io.rulelogic.api.MessagePushResponse.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.rulelogic.api.MessagePushResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.rulelogic.api.MessagePushResponse}
 */
proto.io.rulelogic.api.MessagePushResponse.deserializeBinaryFromReader =
  function (msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
        case 1:
          var value = new common_common_pb.ResponseStatus();
          reader.readMessage(
            value,
            common_common_pb.ResponseStatus.deserializeBinaryFromReader
          );
          msg.setResponsestatus(value);
          break;
        default:
          reader.skipField();
          break;
      }
    }
    return msg;
  };

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.rulelogic.api.MessagePushResponse.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter();
    proto.io.rulelogic.api.MessagePushResponse.serializeBinaryToWriter(
      this,
      writer
    );
    return writer.getResultBuffer();
  };

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.rulelogic.api.MessagePushResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rulelogic.api.MessagePushResponse.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined;
  f = message.getResponsestatus();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_common_pb.ResponseStatus.serializeBinaryToWriter
    );
  }
};

/**
 * optional ResponseStatus responseStatus = 1;
 * @return {?proto.io.rulelogic.api.ResponseStatus}
 */
proto.io.rulelogic.api.MessagePushResponse.prototype.getResponsestatus =
  function () {
    return /** @type{?proto.io.rulelogic.api.ResponseStatus} */ (
      jspb.Message.getWrapperField(this, common_common_pb.ResponseStatus, 1)
    );
  };

/**
 * @param {?proto.io.rulelogic.api.ResponseStatus|undefined} value
 * @return {!proto.io.rulelogic.api.MessagePushResponse} returns this
 */
proto.io.rulelogic.api.MessagePushResponse.prototype.setResponsestatus =
  function (value) {
    return jspb.Message.setWrapperField(this, 1, value);
  };

/**
 * Clears the message field making it undefined.
 * @return {!proto.io.rulelogic.api.MessagePushResponse} returns this
 */
proto.io.rulelogic.api.MessagePushResponse.prototype.clearResponsestatus =
  function () {
    return this.setResponsestatus(undefined);
  };

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.rulelogic.api.MessagePushResponse.prototype.hasResponsestatus =
  function () {
    return jspb.Message.getField(this, 1) != null;
  };

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.io.rulelogic.api.MessagePullRequest.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.io.rulelogic.api.MessagePullRequest.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.io.rulelogic.api.MessagePullRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.io.rulelogic.api.MessagePullRequest.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        messagesubscription: jspb.Message.getFieldWithDefault(msg, 2, 0),
        authdetail:
          (f = msg.getAuthdetail()) &&
          common_common_pb.AuthDetail.toObject(includeInstance, f),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.rulelogic.api.MessagePullRequest}
 */
proto.io.rulelogic.api.MessagePullRequest.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.rulelogic.api.MessagePullRequest();
  return proto.io.rulelogic.api.MessagePullRequest.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.rulelogic.api.MessagePullRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.rulelogic.api.MessagePullRequest}
 */
proto.io.rulelogic.api.MessagePullRequest.deserializeBinaryFromReader =
  function (msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
        case 2:
          var value =
            /** @type {!proto.io.rulelogic.api.messageSubscriptionEnum} */ (
              reader.readEnum()
            );
          msg.setMessagesubscription(value);
          break;
        case 10:
          var value = new common_common_pb.AuthDetail();
          reader.readMessage(
            value,
            common_common_pb.AuthDetail.deserializeBinaryFromReader
          );
          msg.setAuthdetail(value);
          break;
        default:
          reader.skipField();
          break;
      }
    }
    return msg;
  };

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.rulelogic.api.MessagePullRequest.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter();
    proto.io.rulelogic.api.MessagePullRequest.serializeBinaryToWriter(
      this,
      writer
    );
    return writer.getResultBuffer();
  };

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.rulelogic.api.MessagePullRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rulelogic.api.MessagePullRequest.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined;
  f = message.getMessagesubscription();
  if (f !== 0.0) {
    writer.writeEnum(2, f);
  }
  f = message.getAuthdetail();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      common_common_pb.AuthDetail.serializeBinaryToWriter
    );
  }
};

/**
 * optional messageSubscriptionEnum messageSubscription = 2;
 * @return {!proto.io.rulelogic.api.messageSubscriptionEnum}
 */
proto.io.rulelogic.api.MessagePullRequest.prototype.getMessagesubscription =
  function () {
    return /** @type {!proto.io.rulelogic.api.messageSubscriptionEnum} */ (
      jspb.Message.getFieldWithDefault(this, 2, 0)
    );
  };

/**
 * @param {!proto.io.rulelogic.api.messageSubscriptionEnum} value
 * @return {!proto.io.rulelogic.api.MessagePullRequest} returns this
 */
proto.io.rulelogic.api.MessagePullRequest.prototype.setMessagesubscription =
  function (value) {
    return jspb.Message.setProto3EnumField(this, 2, value);
  };

/**
 * optional AuthDetail authDetail = 10;
 * @return {?proto.io.rulelogic.api.AuthDetail}
 */
proto.io.rulelogic.api.MessagePullRequest.prototype.getAuthdetail =
  function () {
    return /** @type{?proto.io.rulelogic.api.AuthDetail} */ (
      jspb.Message.getWrapperField(this, common_common_pb.AuthDetail, 10)
    );
  };

/**
 * @param {?proto.io.rulelogic.api.AuthDetail|undefined} value
 * @return {!proto.io.rulelogic.api.MessagePullRequest} returns this
 */
proto.io.rulelogic.api.MessagePullRequest.prototype.setAuthdetail = function (
  value
) {
  return jspb.Message.setWrapperField(this, 10, value);
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.io.rulelogic.api.MessagePullRequest} returns this
 */
proto.io.rulelogic.api.MessagePullRequest.prototype.clearAuthdetail =
  function () {
    return this.setAuthdetail(undefined);
  };

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.rulelogic.api.MessagePullRequest.prototype.hasAuthdetail =
  function () {
    return jspb.Message.getField(this, 10) != null;
  };

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.io.rulelogic.api.MessagePushRequest.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.io.rulelogic.api.MessagePushRequest.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.io.rulelogic.api.MessagePushRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.io.rulelogic.api.MessagePushRequest.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        payload:
          (f = msg.getPayload()) &&
          proto.io.rulelogic.api.Payload.toObject(includeInstance, f),
        authdetail:
          (f = msg.getAuthdetail()) &&
          common_common_pb.AuthDetail.toObject(includeInstance, f),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.rulelogic.api.MessagePushRequest}
 */
proto.io.rulelogic.api.MessagePushRequest.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.rulelogic.api.MessagePushRequest();
  return proto.io.rulelogic.api.MessagePushRequest.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.rulelogic.api.MessagePushRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.rulelogic.api.MessagePushRequest}
 */
proto.io.rulelogic.api.MessagePushRequest.deserializeBinaryFromReader =
  function (msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
        case 1:
          var value = new proto.io.rulelogic.api.Payload();
          reader.readMessage(
            value,
            proto.io.rulelogic.api.Payload.deserializeBinaryFromReader
          );
          msg.setPayload(value);
          break;
        case 10:
          var value = new common_common_pb.AuthDetail();
          reader.readMessage(
            value,
            common_common_pb.AuthDetail.deserializeBinaryFromReader
          );
          msg.setAuthdetail(value);
          break;
        default:
          reader.skipField();
          break;
      }
    }
    return msg;
  };

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.rulelogic.api.MessagePushRequest.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter();
    proto.io.rulelogic.api.MessagePushRequest.serializeBinaryToWriter(
      this,
      writer
    );
    return writer.getResultBuffer();
  };

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.rulelogic.api.MessagePushRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rulelogic.api.MessagePushRequest.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined;
  f = message.getPayload();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.io.rulelogic.api.Payload.serializeBinaryToWriter
    );
  }
  f = message.getAuthdetail();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      common_common_pb.AuthDetail.serializeBinaryToWriter
    );
  }
};

/**
 * optional Payload payload = 1;
 * @return {?proto.io.rulelogic.api.Payload}
 */
proto.io.rulelogic.api.MessagePushRequest.prototype.getPayload = function () {
  return /** @type{?proto.io.rulelogic.api.Payload} */ (
    jspb.Message.getWrapperField(this, proto.io.rulelogic.api.Payload, 1)
  );
};

/**
 * @param {?proto.io.rulelogic.api.Payload|undefined} value
 * @return {!proto.io.rulelogic.api.MessagePushRequest} returns this
 */
proto.io.rulelogic.api.MessagePushRequest.prototype.setPayload = function (
  value
) {
  return jspb.Message.setWrapperField(this, 1, value);
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.io.rulelogic.api.MessagePushRequest} returns this
 */
proto.io.rulelogic.api.MessagePushRequest.prototype.clearPayload = function () {
  return this.setPayload(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.rulelogic.api.MessagePushRequest.prototype.hasPayload = function () {
  return jspb.Message.getField(this, 1) != null;
};

/**
 * optional AuthDetail authDetail = 10;
 * @return {?proto.io.rulelogic.api.AuthDetail}
 */
proto.io.rulelogic.api.MessagePushRequest.prototype.getAuthdetail =
  function () {
    return /** @type{?proto.io.rulelogic.api.AuthDetail} */ (
      jspb.Message.getWrapperField(this, common_common_pb.AuthDetail, 10)
    );
  };

/**
 * @param {?proto.io.rulelogic.api.AuthDetail|undefined} value
 * @return {!proto.io.rulelogic.api.MessagePushRequest} returns this
 */
proto.io.rulelogic.api.MessagePushRequest.prototype.setAuthdetail = function (
  value
) {
  return jspb.Message.setWrapperField(this, 10, value);
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.io.rulelogic.api.MessagePushRequest} returns this
 */
proto.io.rulelogic.api.MessagePushRequest.prototype.clearAuthdetail =
  function () {
    return this.setAuthdetail(undefined);
  };

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.rulelogic.api.MessagePushRequest.prototype.hasAuthdetail =
  function () {
    return jspb.Message.getField(this, 10) != null;
  };

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.io.rulelogic.api.Payload.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.io.rulelogic.api.Payload.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.io.rulelogic.api.Payload} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.io.rulelogic.api.Payload.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        messagetopic: jspb.Message.getFieldWithDefault(msg, 1, 0),
        instructiontype: jspb.Message.getFieldWithDefault(msg, 2, 0),
        eventinstruction: jspb.Message.getFieldWithDefault(msg, 3, 0),
        ruleinstruction: jspb.Message.getFieldWithDefault(msg, 4, 0),
        actioninstruction: jspb.Message.getFieldWithDefault(msg, 5, 0),
        changestatusfrom: jspb.Message.getFieldWithDefault(msg, 6, 0),
        changestatusto: jspb.Message.getFieldWithDefault(msg, 7, 0),
        partypk: jspb.Message.getFieldWithDefault(msg, 8, ''),
        eventmessagereason: jspb.Message.getFieldWithDefault(msg, 9, 0),
        rulemessagereason: jspb.Message.getFieldWithDefault(msg, 10, 0),
        messagetimestamp: jspb.Message.getFieldWithDefault(msg, 11, ''),
        messagetimestampepoc: jspb.Message.getFieldWithDefault(msg, 12, ''),
        eventrecordpk: jspb.Message.getFieldWithDefault(msg, 13, ''),
        rulerecordpk: jspb.Message.getFieldWithDefault(msg, 14, ''),
        actionrecordpk: jspb.Message.getFieldWithDefault(msg, 15, ''),
        subscriberpartypk: jspb.Message.getFieldWithDefault(msg, 16, ''),
        actiontype: jspb.Message.getFieldWithDefault(msg, 17, 0),
        recordownerpartypk: jspb.Message.getFieldWithDefault(msg, 18, ''),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.rulelogic.api.Payload}
 */
proto.io.rulelogic.api.Payload.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.rulelogic.api.Payload();
  return proto.io.rulelogic.api.Payload.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.rulelogic.api.Payload} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.rulelogic.api.Payload}
 */
proto.io.rulelogic.api.Payload.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {!proto.io.rulelogic.api.messageTopicEnum} */ (
          reader.readEnum()
        );
        msg.setMessagetopic(value);
        break;
      case 2:
        var value = /** @type {!proto.io.rulelogic.api.instructionTypeEnum} */ (
          reader.readEnum()
        );
        msg.setInstructiontype(value);
        break;
      case 3:
        var value =
          /** @type {!proto.io.rulelogic.api.eventInstructionEnum} */ (
            reader.readEnum()
          );
        msg.setEventinstruction(value);
        break;
      case 4:
        var value = /** @type {!proto.io.rulelogic.api.ruleInstructionEnum} */ (
          reader.readEnum()
        );
        msg.setRuleinstruction(value);
        break;
      case 5:
        var value =
          /** @type {!proto.io.rulelogic.api.actionInstructionEnum} */ (
            reader.readEnum()
          );
        msg.setActioninstruction(value);
        break;
      case 6:
        var value = /** @type {!proto.io.rulelogic.api.statusEnum} */ (
          reader.readEnum()
        );
        msg.setChangestatusfrom(value);
        break;
      case 7:
        var value = /** @type {!proto.io.rulelogic.api.statusEnum} */ (
          reader.readEnum()
        );
        msg.setChangestatusto(value);
        break;
      case 8:
        var value = /** @type {string} */ (reader.readString());
        msg.setPartypk(value);
        break;
      case 9:
        var value =
          /** @type {!proto.io.rulelogic.api.eventMessageReasonEnum} */ (
            reader.readEnum()
          );
        msg.setEventmessagereason(value);
        break;
      case 10:
        var value =
          /** @type {!proto.io.rulelogic.api.ruleMessageReasonEnum} */ (
            reader.readEnum()
          );
        msg.setRulemessagereason(value);
        break;
      case 11:
        var value = /** @type {string} */ (reader.readString());
        msg.setMessagetimestamp(value);
        break;
      case 12:
        var value = /** @type {string} */ (reader.readString());
        msg.setMessagetimestampepoc(value);
        break;
      case 13:
        var value = /** @type {string} */ (reader.readString());
        msg.setEventrecordpk(value);
        break;
      case 14:
        var value = /** @type {string} */ (reader.readString());
        msg.setRulerecordpk(value);
        break;
      case 15:
        var value = /** @type {string} */ (reader.readString());
        msg.setActionrecordpk(value);
        break;
      case 16:
        var value = /** @type {string} */ (reader.readString());
        msg.setSubscriberpartypk(value);
        break;
      case 17:
        var value = /** @type {!proto.io.rulelogic.api.actionTypeEnum} */ (
          reader.readEnum()
        );
        msg.setActiontype(value);
        break;
      case 18:
        var value = /** @type {string} */ (reader.readString());
        msg.setRecordownerpartypk(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.rulelogic.api.Payload.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.io.rulelogic.api.Payload.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.rulelogic.api.Payload} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rulelogic.api.Payload.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined;
  f = message.getMessagetopic();
  if (f !== 0.0) {
    writer.writeEnum(1, f);
  }
  f = message.getInstructiontype();
  if (f !== 0.0) {
    writer.writeEnum(2, f);
  }
  f = message.getEventinstruction();
  if (f !== 0.0) {
    writer.writeEnum(3, f);
  }
  f = message.getRuleinstruction();
  if (f !== 0.0) {
    writer.writeEnum(4, f);
  }
  f = message.getActioninstruction();
  if (f !== 0.0) {
    writer.writeEnum(5, f);
  }
  f = message.getChangestatusfrom();
  if (f !== 0.0) {
    writer.writeEnum(6, f);
  }
  f = message.getChangestatusto();
  if (f !== 0.0) {
    writer.writeEnum(7, f);
  }
  f = message.getPartypk();
  if (f.length > 0) {
    writer.writeString(8, f);
  }
  f = message.getEventmessagereason();
  if (f !== 0.0) {
    writer.writeEnum(9, f);
  }
  f = message.getRulemessagereason();
  if (f !== 0.0) {
    writer.writeEnum(10, f);
  }
  f = message.getMessagetimestamp();
  if (f.length > 0) {
    writer.writeString(11, f);
  }
  f = message.getMessagetimestampepoc();
  if (f.length > 0) {
    writer.writeString(12, f);
  }
  f = message.getEventrecordpk();
  if (f.length > 0) {
    writer.writeString(13, f);
  }
  f = message.getRulerecordpk();
  if (f.length > 0) {
    writer.writeString(14, f);
  }
  f = message.getActionrecordpk();
  if (f.length > 0) {
    writer.writeString(15, f);
  }
  f = message.getSubscriberpartypk();
  if (f.length > 0) {
    writer.writeString(16, f);
  }
  f = message.getActiontype();
  if (f !== 0.0) {
    writer.writeEnum(17, f);
  }
  f = message.getRecordownerpartypk();
  if (f.length > 0) {
    writer.writeString(18, f);
  }
};

/**
 * optional messageTopicEnum messageTopic = 1;
 * @return {!proto.io.rulelogic.api.messageTopicEnum}
 */
proto.io.rulelogic.api.Payload.prototype.getMessagetopic = function () {
  return /** @type {!proto.io.rulelogic.api.messageTopicEnum} */ (
    jspb.Message.getFieldWithDefault(this, 1, 0)
  );
};

/**
 * @param {!proto.io.rulelogic.api.messageTopicEnum} value
 * @return {!proto.io.rulelogic.api.Payload} returns this
 */
proto.io.rulelogic.api.Payload.prototype.setMessagetopic = function (value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};

/**
 * optional instructionTypeEnum instructionType = 2;
 * @return {!proto.io.rulelogic.api.instructionTypeEnum}
 */
proto.io.rulelogic.api.Payload.prototype.getInstructiontype = function () {
  return /** @type {!proto.io.rulelogic.api.instructionTypeEnum} */ (
    jspb.Message.getFieldWithDefault(this, 2, 0)
  );
};

/**
 * @param {!proto.io.rulelogic.api.instructionTypeEnum} value
 * @return {!proto.io.rulelogic.api.Payload} returns this
 */
proto.io.rulelogic.api.Payload.prototype.setInstructiontype = function (value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};

/**
 * optional eventInstructionEnum eventInstruction = 3;
 * @return {!proto.io.rulelogic.api.eventInstructionEnum}
 */
proto.io.rulelogic.api.Payload.prototype.getEventinstruction = function () {
  return /** @type {!proto.io.rulelogic.api.eventInstructionEnum} */ (
    jspb.Message.getFieldWithDefault(this, 3, 0)
  );
};

/**
 * @param {!proto.io.rulelogic.api.eventInstructionEnum} value
 * @return {!proto.io.rulelogic.api.Payload} returns this
 */
proto.io.rulelogic.api.Payload.prototype.setEventinstruction = function (
  value
) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};

/**
 * optional ruleInstructionEnum ruleInstruction = 4;
 * @return {!proto.io.rulelogic.api.ruleInstructionEnum}
 */
proto.io.rulelogic.api.Payload.prototype.getRuleinstruction = function () {
  return /** @type {!proto.io.rulelogic.api.ruleInstructionEnum} */ (
    jspb.Message.getFieldWithDefault(this, 4, 0)
  );
};

/**
 * @param {!proto.io.rulelogic.api.ruleInstructionEnum} value
 * @return {!proto.io.rulelogic.api.Payload} returns this
 */
proto.io.rulelogic.api.Payload.prototype.setRuleinstruction = function (value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};

/**
 * optional actionInstructionEnum actionInstruction = 5;
 * @return {!proto.io.rulelogic.api.actionInstructionEnum}
 */
proto.io.rulelogic.api.Payload.prototype.getActioninstruction = function () {
  return /** @type {!proto.io.rulelogic.api.actionInstructionEnum} */ (
    jspb.Message.getFieldWithDefault(this, 5, 0)
  );
};

/**
 * @param {!proto.io.rulelogic.api.actionInstructionEnum} value
 * @return {!proto.io.rulelogic.api.Payload} returns this
 */
proto.io.rulelogic.api.Payload.prototype.setActioninstruction = function (
  value
) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};

/**
 * optional statusEnum changeStatusFrom = 6;
 * @return {!proto.io.rulelogic.api.statusEnum}
 */
proto.io.rulelogic.api.Payload.prototype.getChangestatusfrom = function () {
  return /** @type {!proto.io.rulelogic.api.statusEnum} */ (
    jspb.Message.getFieldWithDefault(this, 6, 0)
  );
};

/**
 * @param {!proto.io.rulelogic.api.statusEnum} value
 * @return {!proto.io.rulelogic.api.Payload} returns this
 */
proto.io.rulelogic.api.Payload.prototype.setChangestatusfrom = function (
  value
) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};

/**
 * optional statusEnum changeStatusTo = 7;
 * @return {!proto.io.rulelogic.api.statusEnum}
 */
proto.io.rulelogic.api.Payload.prototype.getChangestatusto = function () {
  return /** @type {!proto.io.rulelogic.api.statusEnum} */ (
    jspb.Message.getFieldWithDefault(this, 7, 0)
  );
};

/**
 * @param {!proto.io.rulelogic.api.statusEnum} value
 * @return {!proto.io.rulelogic.api.Payload} returns this
 */
proto.io.rulelogic.api.Payload.prototype.setChangestatusto = function (value) {
  return jspb.Message.setProto3EnumField(this, 7, value);
};

/**
 * optional string partyPk = 8;
 * @return {string}
 */
proto.io.rulelogic.api.Payload.prototype.getPartypk = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ''));
};

/**
 * @param {string} value
 * @return {!proto.io.rulelogic.api.Payload} returns this
 */
proto.io.rulelogic.api.Payload.prototype.setPartypk = function (value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};

/**
 * optional eventMessageReasonEnum eventMessageReason = 9;
 * @return {!proto.io.rulelogic.api.eventMessageReasonEnum}
 */
proto.io.rulelogic.api.Payload.prototype.getEventmessagereason = function () {
  return /** @type {!proto.io.rulelogic.api.eventMessageReasonEnum} */ (
    jspb.Message.getFieldWithDefault(this, 9, 0)
  );
};

/**
 * @param {!proto.io.rulelogic.api.eventMessageReasonEnum} value
 * @return {!proto.io.rulelogic.api.Payload} returns this
 */
proto.io.rulelogic.api.Payload.prototype.setEventmessagereason = function (
  value
) {
  return jspb.Message.setProto3EnumField(this, 9, value);
};

/**
 * optional ruleMessageReasonEnum ruleMessageReason = 10;
 * @return {!proto.io.rulelogic.api.ruleMessageReasonEnum}
 */
proto.io.rulelogic.api.Payload.prototype.getRulemessagereason = function () {
  return /** @type {!proto.io.rulelogic.api.ruleMessageReasonEnum} */ (
    jspb.Message.getFieldWithDefault(this, 10, 0)
  );
};

/**
 * @param {!proto.io.rulelogic.api.ruleMessageReasonEnum} value
 * @return {!proto.io.rulelogic.api.Payload} returns this
 */
proto.io.rulelogic.api.Payload.prototype.setRulemessagereason = function (
  value
) {
  return jspb.Message.setProto3EnumField(this, 10, value);
};

/**
 * optional string messageTimestamp = 11;
 * @return {string}
 */
proto.io.rulelogic.api.Payload.prototype.getMessagetimestamp = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ''));
};

/**
 * @param {string} value
 * @return {!proto.io.rulelogic.api.Payload} returns this
 */
proto.io.rulelogic.api.Payload.prototype.setMessagetimestamp = function (
  value
) {
  return jspb.Message.setProto3StringField(this, 11, value);
};

/**
 * optional string messageTimestampEpoc = 12;
 * @return {string}
 */
proto.io.rulelogic.api.Payload.prototype.getMessagetimestampepoc = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ''));
};

/**
 * @param {string} value
 * @return {!proto.io.rulelogic.api.Payload} returns this
 */
proto.io.rulelogic.api.Payload.prototype.setMessagetimestampepoc = function (
  value
) {
  return jspb.Message.setProto3StringField(this, 12, value);
};

/**
 * optional string eventRecordPk = 13;
 * @return {string}
 */
proto.io.rulelogic.api.Payload.prototype.getEventrecordpk = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ''));
};

/**
 * @param {string} value
 * @return {!proto.io.rulelogic.api.Payload} returns this
 */
proto.io.rulelogic.api.Payload.prototype.setEventrecordpk = function (value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};

/**
 * optional string ruleRecordPk = 14;
 * @return {string}
 */
proto.io.rulelogic.api.Payload.prototype.getRulerecordpk = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ''));
};

/**
 * @param {string} value
 * @return {!proto.io.rulelogic.api.Payload} returns this
 */
proto.io.rulelogic.api.Payload.prototype.setRulerecordpk = function (value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};

/**
 * optional string actionRecordPk = 15;
 * @return {string}
 */
proto.io.rulelogic.api.Payload.prototype.getActionrecordpk = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ''));
};

/**
 * @param {string} value
 * @return {!proto.io.rulelogic.api.Payload} returns this
 */
proto.io.rulelogic.api.Payload.prototype.setActionrecordpk = function (value) {
  return jspb.Message.setProto3StringField(this, 15, value);
};

/**
 * optional string subscriberPartyPk = 16;
 * @return {string}
 */
proto.io.rulelogic.api.Payload.prototype.getSubscriberpartypk = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ''));
};

/**
 * @param {string} value
 * @return {!proto.io.rulelogic.api.Payload} returns this
 */
proto.io.rulelogic.api.Payload.prototype.setSubscriberpartypk = function (
  value
) {
  return jspb.Message.setProto3StringField(this, 16, value);
};

/**
 * optional actionTypeEnum actionType = 17;
 * @return {!proto.io.rulelogic.api.actionTypeEnum}
 */
proto.io.rulelogic.api.Payload.prototype.getActiontype = function () {
  return /** @type {!proto.io.rulelogic.api.actionTypeEnum} */ (
    jspb.Message.getFieldWithDefault(this, 17, 0)
  );
};

/**
 * @param {!proto.io.rulelogic.api.actionTypeEnum} value
 * @return {!proto.io.rulelogic.api.Payload} returns this
 */
proto.io.rulelogic.api.Payload.prototype.setActiontype = function (value) {
  return jspb.Message.setProto3EnumField(this, 17, value);
};

/**
 * optional string recordOwnerPartyPk = 18;
 * @return {string}
 */
proto.io.rulelogic.api.Payload.prototype.getRecordownerpartypk = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 18, ''));
};

/**
 * @param {string} value
 * @return {!proto.io.rulelogic.api.Payload} returns this
 */
proto.io.rulelogic.api.Payload.prototype.setRecordownerpartypk = function (
  value
) {
  return jspb.Message.setProto3StringField(this, 18, value);
};

/**
 * @enum {number}
 */
proto.io.rulelogic.api.messageTopicEnum = {
  EVENT: 0,
  RULE: 1,
  ACTION: 2,
};

/**
 * @enum {number}
 */
proto.io.rulelogic.api.messageSubscriptionEnum = {
  EVENT_SUB: 0,
  RULE_SUB: 1,
  ACTION_SUB: 2,
  ACTION_EMAIL_SUB: 3,
  ACTION_SMS_SUB: 4,
  ACTION_VOICE_SUB: 5,
  ACTION_API_SUB: 6,
  ACTION_TWEET_SUB: 7,
  ACTION_PING_SUB: 8,
  ACTION_CALLBACK_SUB: 9,
  ACTION_NOTIFICATION_SUB: 10,
};

/**
 * @enum {number}
 */
proto.io.rulelogic.api.instructionTypeEnum = {
  ACTION_REQUESTED: 0,
  ACTION_DO: 1,
  ACTION_DONE: 2,
};

/**
 * @enum {number}
 */
proto.io.rulelogic.api.eventInstructionEnum = {
  TURN_ON_EVENT: 0,
  TURN_OFF_EVENT: 1,
  CHECK_EVENT_STATUS: 2,
};

/**
 * @enum {number}
 */
proto.io.rulelogic.api.ruleInstructionEnum = {
  TURN_ON_RULE: 0,
  TURN_OFF_RULE: 1,
  CHECK_RULE_STATUS: 2,
};

/**
 * @enum {number}
 */
proto.io.rulelogic.api.actionInstructionEnum = {
  DO_ACTION: 0,
  GENERATE_ACTION_CONTENT: 1,
};

/**
 * @enum {number}
 */
proto.io.rulelogic.api.statusEnum = {
  OFF: 0,
  ON: 1,
};

/**
 * @enum {number}
 */
proto.io.rulelogic.api.eventMessageReasonEnum = {
  EVENT_STATUS_CHANGED_NORMALLY: 0,
  EVENT_STATUS_CHANGED_MANUALLY: 1,
};

/**
 * @enum {number}
 */
proto.io.rulelogic.api.ruleMessageReasonEnum = {
  RULE_STATUS_CHANGED_NORMALLY: 0,
  RULE_STATUS_CHANGED_MANUALLY: 1,
};

goog.object.extend(exports, proto.io.rulelogic.api);
